import type { Metadata } from 'next'
import './globalStyles/globals.scss'
import './globalStyles/normalize.css'
import Layout from './components/layouts/Layouts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
